version: '2'
services:
  postgresdbserver:
    image: postgres:17.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=sysml2
    ports:
      - "5432:5432"
    volumes:
      - postgresdbserver:/var/lib/postgresql/data

  sysmlapiserver:
    image: "sysml.api:${RELEASE}"
    tty: true
    links:
      - postgresdbserver
    ports:
      - "9000:9000"
    restart: always

  sysmljupyter:
    image: "sysml.jupyter:${SYSML_RELEASE}"
    links:
      - sysmlapiserver
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - "./mydata:/home/sysml/SysML-v2-Release-${SYSML_RELEASE}/mydata"

networks:
  default:
    external:
      name: thenetwork

volumes:
  postgresdbserver:
    external: true
